### ISSUE TITLE
High timings value on PlayerJoin! (Laggs?)

### ISSUE THREAD

**Issue by helptiger** [sgtcaze/NametagEdit#37]
It seems, that the plugin causes laggs on PlayerJoin!?
![untitled](https://cloud.githubusercontent.com/assets/10258902/7477954/8e8ad620-f357-11e4-99d5-a7d48c82f340.png)

**Comment by Agazed** [comment]
Getting this too. Please fix this

**Comment by sgtcaze** [comment]
This was fixed a few weeks ago in this commit: 

https://github.com/sgtcaze/NametagEdit/commit/fa4fe4c40a32e3fefce924617b1edcb56182f1df

**Comment by Agazed** [comment]
Still getting high readings with the latest version. Just compiled it.

http://timings.aikar.co/?url=11358455

**Comment by Agazed** [comment]
This is causing massive lag on my server. Going to have to find a different plugin for now.

**Comment by sgtcaze** [comment]
Closing this for now. Going to promote a release candidate after some more bug fixes, then we'll re-address the issue.
